### ISSUE TITLE
Nonlinear solver

### ISSUE THREAD

**Issue by linwaytin** [FreeFem/FreeFem-sources#114]
Hi there, 

I am working on a nonlinear PDE.
It seems the "problem" supports only a linear problem,
and users have to write nonlinear solvers by themselves like this 
https://www.um.es/freefem/ff++/pmwiki.php?n=Main.NonlinearEllipticEquation

However I do see FreeFEM++ has interface to PETSc, which contains nonlinear solvers.
Is there any way I can solve a nonlinear problem easily, just like linear problems?

Thank you.

**Comment by prj-** [comment]
Sure, here are some examples:

- [plain Newton](https://github.com/FreeFem/FreeFem-sources/blob/master/examples/hpddm/Newton-2d-PETSc.edp)
- [Newton with mesh adaptation](https://github.com/FreeFem/FreeFem-sources/blob/master/examples/hpddm/Newton-adaptmesh-2d-PETSc.edp)
- [Newton with variational inequalities](https://github.com/FreeFem/FreeFem-sources/blob/master/examples/hpddm/Newton-vi-2d-PETSc.edp)
- [Newton with variational inequalities and mesh adaptation](https://github.com/FreeFem/FreeFem-sources/blob/master/examples/hpddm/Newton-vi-adaptmesh-2d-PETSc.edp)
- [Liouville–Bratu–Gelfand equation](https://github.com/FreeFem/FreeFem-sources/blob/master/examples/hpddm/bratu-2d-PETSc.edp)
- [minimal surface problem](https://github.com/FreeFem/FreeFem-sources/blob/master/examples/hpddm/minimal-surface-2d-Tao-PETSc.edp)
- [Neo-Hookean nonlinear elasticity](https://github.com/FreeFem/FreeFem-sources/blob/master/examples/hpddm/neo-Hookean-2d-PETSc.edp)

These examples are in 2D so that it is easier to visualize results, but of course, it works in 3D as well.

**Comment by linwaytin** [comment]
Thank you so much. That's what I want.

The tutorial looks perfect. I would suggest putting those links to the official website.
I never found them on the Internet. (This is probably due to my poor searching technique.)
It would be better that people can find these resources on the official website.

**Comment by prj-** [comment]
Thank you for your kind words. I'll put a link in the documentation to the tutorial. Unless you have further questions, could you please close the issue? If you have very specific issues, you can always contact me via email directly later on. Thanks.

**Comment by linwaytin** [comment]
Thank you.
