### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by sgarnotel** [FreeFem/FreeFem-sources#31]
A coverage report is available [here](http://13.93.1.249/coverage/)
It will be good to reach, at least, 80% of coverage for Lines and Functions.

PS: There is no automatic update at each commit right now but that will be done in the future

**Comment by cdoucet** [comment]
Very interesting. 

If I understand well, lcov is a dynamic static analyzer. It means that results depends on which version of FreeFem you generated and which example you ran. It is right? In this case, it may be informative to produce a report for several generations of FreeFem (with or without download, with or without installed package). Some parts of the code may be involved in only one scenario. 

I wonder if there exists a static analyzer which is able to take preprocessor directives into account in order to build a tree to detect dead code. It could be a good complement to lcov. I know that such products exist for professional software testers but I don't know if some are freely available. 

If needed, we have also a SonarQube service at Inria: https://sonarqube.bordeaux.inria.fr. I can set it up for you if you're interested in.

I will take a look at the report to see if I can improve some things.

**Comment by sgarnotel** [comment]
Yes, the result is for a specific build, here on the Ubuntu All slave.

I would be interesting to compare results with sonarqube.

**Comment by cdoucet** [comment]
Ok, I will set it up.
