### ISSUE TITLE
Thermal radiation

### ISSUE THREAD

**Issue by sgarnotel** [FreeFem/FreeFem-sources#33]
I currently build a thermal radiation alogrithm using an external software to compute the thermal view factor.
This software returns me a "density map" at each edge center (2D), and I want to import this in FreeFem++ in order to use it directly as a parameter of my thermal radiation problem.

Does anyone know an elgent way to do this ?

PS: I can modify the thermal view factor software output if necessary

**Comment by cdoucet** [comment]
Could you provide the name of the external software? Sometimes, integral values over faces are stored as if they were located on a center node but it is not the case.

**Comment by sgarnotel** [comment]
This is an in-house software, C++ Ray tracer.
The thermal view factor is defined in the center of each boundary edges (by meaning on the edge).

The problem here is to load it in FreeFem

**Comment by sgarnotel** [comment]
Thanks, an field export seems to works well!

**Comment by hbadi** [comment]
Hello @sgarnotel 

I also have the same problem. I want to use the view factor matrix (computed in an external program) of air cavity edges in order to prescribe radiation boundary conditions to a thermal problem. I don't know if freefem can handle "large" boundary radiation conditions ?

Best regards.
