### ISSUE TITLE
Software does not run on MacOS 10.14 Mojave

### ISSUE THREAD

**Issue by laphysiqueaveclesmains** [FreeFem/FreeFem-sources#68]
Hi there !

I am a long-time user of the FreeFEM suite on Mac OS X platforms (I started using early versions around 2000). Everything has always run smoothly on all my machines until now.

**The latest full version (3.61), which ran perfectly on Mac OS 10.13, suddenly stopped executing as soon as I upgraded to Mac OS 10.14**. The 4.0 beta version does not seem to run on that version of the OS either. Note that I witnessed the same problem on different machines (Macbook and Macbook Pro), so it definitely seems to be an issue with the OS and not with the machine architecture.

Any clue as to how I may solve this problem ?
Thank you,

Pierre Carles
Sorbonne Université

**Comment by frederichecht** [comment]
Dear  user

For me version 4beta run on Mojave 
I have tested 

You can send more info to help me
Frédéric

**Comment by frederichecht** [comment]
Dear user,

I now one big  problem on Mojave , 

The graphic e window is black,  first to help you you can resize the graphic-c window then general the graphic appear.

Otherwise the 	version FreeFem++-4.0-MacOS_10.11.pkg 387 MB <https://github.com/FreeFem/FreeFem-sources/releases/download/v4-beta/FreeFem++-4.0-MacOS_10.11.pkg>  run under mojave.


Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by laphysiqueaveclesmains** [comment]
I will try to install the 10.11 version as you suggested and let you know if it works.

If there is a way for me to pipe the compiler's errors to a log file, please let me know: maybe I can grab error messages then, that would make sense to you.

Thank you again for your help. I am using FreeFEM++ both as an engineering tool for my research and as a training tool for my students, and it has been a priceless asset.
Best,

Pierre

**Comment by laphysiqueaveclesmains** [comment]
OK, wait !

I just tried to run the code in command line from a Terminal window, and things seemed to work fine (sorry that I did not think of trying this earlier) ! In other words, it seems that the issue appears only when I start the code by double-clicking on the FreeFEM++ icon in the Application folder.
This would make the issue minor then. I will let you know if everything runs smoothly.

However, I remain interested in any clue regarding launching the code as an Application: not all my students are familiar with command line (fools !), and it will make life easier on them if they can simply double-click on an icon to run FreeFEM++

Once again, a big thank-you for getting back to me swiftly,
Best regards,

Pierre

**Comment by frederichecht** [comment]
Dear user (no name)

I know that  M%ojave  add security stuff, 

If you use a application FreeFem++.app possibly the application  have no right to open the terminal. 

You can try directly in the terminal 
FreeFem++ test.edp



Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++



Please reinstall FreeFem++ form
on Mac version El Capitain (10.11.6) or better  http://www3.freefem.org/ff++/ftp/FreeFem++-4.0-MacOS_10.11.pkg <http://www3.freefem.org/ff++/ftp/FreeFem++-4.0-MacOS_10.11.pkg> ( 387.5 Mb, Jan 18, 2019 17:36:05.)

**Comment by frederichecht** [comment]
Pierr,

You can use textmate or atom test editor  to launch directly frefem++ form this editor
see
Download TextMate 2.0 <https://api.textmate.org/downloads/release?os=10.9>

and follow: 
https://github.com/FreeFem/FreeFem-parser-textmate

Or from  atom but more complex  launch freefem from the editor.
